# Generated by MOIRA from the diagram.
# Contraction order: greedy heuristic.
# Estimated cost: 7696 operations; scaling O(χ^2·2^2).
# Largest intermediate: 512 elements.
#
# The tensors below are YOUR input. The random block exists only so this
# snippet runs as-is; replace it with your own data.

using ITensors

# Indices: the name is the one the equation band shows.
alpha = Index(16, "alpha")
delta = Index(2, "delta")
beta = Index(16, "beta")
epsilon = Index(2, "epsilon")
gamma = Index(16, "gamma")
zeta = Index(2, "zeta")
eta = Index(2, "eta")
theta = Index(8, "theta")
nu = Index(2, "nu")
lambda = Index(8, "lambda")
xi = Index(2, "xi")
mu = Index(8, "mu")
alpha1 = Index(2, "alpha1")
beta1 = Index(2, "beta1")
gamma1 = Index(16, "gamma1")
delta1 = Index(16, "delta1")
epsilon1 = Index(16, "epsilon1")

# Example data — replace with your own tensors.
dados_A1c = randn(16, 2)
dados_A2c = randn(16, 16, 2)
dados_A3c = randn(16, 16, 2)
dados_A4c = randn(16, 2)
dados_W1 = randn(8, 2, 2)
dados_W2 = randn(8, 8, 2, 2)
dados_W3 = randn(8, 8, 2, 2)
dados_W4 = randn(8, 2, 2)
dados_A1 = randn(16, 2)
dados_A2 = randn(16, 16, 2)
dados_A3 = randn(16, 16, 2)
dados_A4 = randn(16, 2)

# Each tensor takes its indices in the axis order of the diagram.
A1c = ITensor(dados_A1c, alpha, delta)  # conjugate
A2c = ITensor(dados_A2c, alpha, beta, epsilon)  # conjugate
A3c = ITensor(dados_A3c, beta, gamma, zeta)  # conjugate
A4c = ITensor(dados_A4c, gamma, eta)  # conjugate
W1 = ITensor(dados_W1, theta, delta, nu)
W2 = ITensor(dados_W2, theta, lambda, epsilon, xi)
W3 = ITensor(dados_W3, lambda, mu, zeta, alpha1)
W4 = ITensor(dados_W4, mu, eta, beta1)
A1 = ITensor(dados_A1, gamma1, nu)
A2 = ITensor(dados_A2, gamma1, delta1, xi)
A3 = ITensor(dados_A3, delta1, epsilon1, alpha1)
A4 = ITensor(dados_A4, epsilon1, beta1)

# Contraction in the chosen order:
R1 = A1 * A2
R2 = A3 * A4
R3 = R1 * R2
R4 = W3 * W4
R5 = W1 * W2
R6 = A1c * A2c
R7 = A3c * A4c
R8 = R6 * R7
R9 = R5 * R8
R10 = R4 * R9
R11 = R3 * R10

R = R11
println(scalar(R))
