% Generated by MOIRA from the diagram.
% Contraction order: greedy heuristic.
% Estimated cost: 7696 operations; scaling O(χ^2·2^2).
% Largest intermediate: 512 elements.
%
% The tensors below are YOUR input. The random block exists only so this
% snippet runs as-is; replace it with your own data.
%
% Contracted indices are numbered in the order the chosen path sums them,
% so the sequence argument is simply 1, 2, 3, ...
%
% Tensors marked (conjugate) enter the contraction conjugated:
% pass the conjugated data in those slots.
% A1c: alpha=16 × delta=2  (conjugate)
% A2c: alpha=16 × beta=16 × epsilon=2  (conjugate)
% A3c: beta=16 × gamma=16 × zeta=2  (conjugate)
% A4c: gamma=16 × eta=2  (conjugate)
% W1: theta=8 × delta=2 × nu=2
% W2: theta=8 × lambda=8 × epsilon=2 × xi=2
% W3: lambda=8 × mu=8 × zeta=2 × alpha1=2
% W4: mu=8 × eta=2 × beta1=2
% A1: gamma1=16 × nu=2
% A2: gamma1=16 × delta1=16 × xi=2
% A3: delta1=16 × epsilon1=16 × alpha1=2
% A4: epsilon1=16 × beta1=2

% Example data — replace with your own tensors.
% Conjugate tensors get independent random data here, not the
% conjugate of their partner — MOIRA marks that a tensor is
% conjugated, not whose conjugate it is.
A1c = rand([16 2]);
A2c = rand([16 16 2]);
A3c = rand([16 16 2]);
A4c = rand([16 2]);
W1 = rand([8 2 2]);
W2 = rand([8 8 2 2]);
W3 = rand([8 8 2 2]);
W4 = rand([8 2 2]);
A1 = rand([16 2]);
A2 = rand([16 16 2]);
A3 = rand([16 16 2]);
A4 = rand([16 2]);

tensores = {A1c, A2c, A3c, A4c, W1, W2, W3, W4, A1, A2, A3, A4};
indices  = {[6 9], [6 8 10], [8 7 12], [7 13], [5 9 14], [5 11 10 15], [11 4 12 16], [4 13 17], [1 14], [1 3 15], [3 2 16], [2 17]};
sequencia = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17];

R = ncon(tensores, indices, sequencia);
disp(R)
