# Generated by MOIRA from the diagram.
# Contraction order: greedy heuristic.
# Estimated cost: 7696 operations; scaling O(χ^2·2^2).
# Largest intermediate: 512 elements.
#
# The tensors below are YOUR input. The random block exists only so this
# snippet runs as-is; replace it with your own data.

import numpy as np
import quimb.tensor as qtn

# Example data — replace with your own tensors.
# Conjugate tensors get independent random data here, not the
# conjugate of their partner — MOIRA marks that a tensor is
# conjugated, not whose conjugate it is.
A1c = np.random.rand(16, 2)
A2c = np.random.rand(16, 16, 2)
A3c = np.random.rand(16, 16, 2)
A4c = np.random.rand(16, 2)
W1 = np.random.rand(8, 2, 2)
W2 = np.random.rand(8, 8, 2, 2)
W3 = np.random.rand(8, 8, 2, 2)
W4 = np.random.rand(8, 2, 2)
A1 = np.random.rand(16, 2)
A2 = np.random.rand(16, 16, 2)
A3 = np.random.rand(16, 16, 2)
A4 = np.random.rand(16, 2)

# A1† — shape (16, 2)
t_A1c = qtn.Tensor(A1c, inds=('alpha', 'delta'), tags=('bra', 'mps'))
# A2† — shape (16, 16, 2)
t_A2c = qtn.Tensor(A2c, inds=('alpha', 'beta', 'epsilon'), tags=('bra', 'mps'))
# A3† — shape (16, 16, 2)
t_A3c = qtn.Tensor(A3c, inds=('beta', 'gamma', 'zeta'), tags=('bra', 'mps'))
# A4† — shape (16, 2)
t_A4c = qtn.Tensor(A4c, inds=('gamma', 'eta'), tags=('bra', 'mps'))
# W1 — shape (8, 2, 2)
t_W1 = qtn.Tensor(W1, inds=('theta', 'delta', 'nu'), tags=('mpo',))
# W2 — shape (8, 8, 2, 2)
t_W2 = qtn.Tensor(W2, inds=('theta', 'lambda', 'epsilon', 'xi'), tags=('mpo',))
# W3 — shape (8, 8, 2, 2)
t_W3 = qtn.Tensor(W3, inds=('lambda', 'mu', 'zeta', 'alpha1'), tags=('mpo',))
# W4 — shape (8, 2, 2)
t_W4 = qtn.Tensor(W4, inds=('mu', 'eta', 'beta1'), tags=('mpo',))
# A1 — shape (16, 2)
t_A1 = qtn.Tensor(A1, inds=('gamma1', 'nu'), tags=('ket', 'mps'))
# A2 — shape (16, 16, 2)
t_A2 = qtn.Tensor(A2, inds=('gamma1', 'delta1', 'xi'), tags=('ket', 'mps'))
# A3 — shape (16, 16, 2)
t_A3 = qtn.Tensor(A3, inds=('delta1', 'epsilon1', 'alpha1'), tags=('ket', 'mps'))
# A4 — shape (16, 2)
t_A4 = qtn.Tensor(A4, inds=('epsilon1', 'beta1'), tags=('ket', 'mps'))

tn = qtn.TensorNetwork([t_A1c, t_A2c, t_A3c, t_A4c, t_W1, t_W2, t_W3, t_W4, t_A1, t_A2, t_A3, t_A4])
R = tn.contract()
print(R)

# tn.draw() desenha a rede — com layout próprio, não com a geometria do
# diagrama. Para a figura que você desenhou, exporte SVG ou TikZ do MOIRA.
