# Generated by MOIRA from the diagram.
# Contraction order: greedy heuristic.
# Estimated cost: 7696 operations; scaling O(χ^2·2^2).
# Largest intermediate: 512 elements.
#
# The tensors below are YOUR input. The random block exists only so this
# snippet runs as-is; replace it with your own data.
#
# Tensors marked (conjugate) enter the contraction conjugated:
# pass the conjugated data in those slots.
# A1c: alpha=16 × delta=2  (conjugate)
# A2c: alpha=16 × beta=16 × epsilon=2  (conjugate)
# A3c: beta=16 × gamma=16 × zeta=2  (conjugate)
# A4c: gamma=16 × eta=2  (conjugate)
# W1: theta=8 × delta=2 × nu=2
# W2: theta=8 × lambda=8 × epsilon=2 × xi=2
# W3: lambda=8 × mu=8 × zeta=2 × alpha1=2
# W4: mu=8 × eta=2 × beta1=2
# A1: gamma1=16 × nu=2
# A2: gamma1=16 × delta1=16 × xi=2
# A3: delta1=16 × epsilon1=16 × alpha1=2
# A4: epsilon1=16 × beta1=2

import numpy as np

# Example data — replace with your own tensors.
# Each language draws its own random numbers, so the value printed
# here is NOT comparable across dialects. Only your own data is.
# Conjugate tensors get independent random data here, not the
# conjugate of their partner — MOIRA marks that a tensor is
# conjugated, not whose conjugate it is.
A1c = np.random.rand(16, 2)
A2c = np.random.rand(16, 16, 2)
A3c = np.random.rand(16, 16, 2)
A4c = np.random.rand(16, 2)
W1 = np.random.rand(8, 2, 2)
W2 = np.random.rand(8, 8, 2, 2)
W3 = np.random.rand(8, 8, 2, 2)
W4 = np.random.rand(8, 2, 2)
A1 = np.random.rand(16, 2)
A2 = np.random.rand(16, 16, 2)
A3 = np.random.rand(16, 16, 2)
A4 = np.random.rand(16, 2)

# The contraction order MOIRA found. numpy takes it directly:
# without it, einsum contracts naively and a network of this size does
# not finish.
caminho = ['einsum_path', (8, 9), (8, 9), (8, 9), (6, 7), (4, 5), (0, 1), (0, 1), (3, 4), (2, 3), (1, 2), (0, 1)]

R = np.einsum('ab,acd,cef,eg,hbi,hjdk,jlfm,lgn,oi,opk,pqm,qn->', A1c, A2c, A3c, A4c, W1, W2, W3, W4, A1, A2, A3, A4, optimize=caminho)
print(R)

# opt_einsum takes the same path, without the leading marker:
# contract('ab,acd,cef,eg,hbi,hjdk,jlfm,lgn,oi,opk,pqm,qn->', A1c, A2c, A3c, A4c, W1, W2, W3, W4, A1, A2, A3, A4, optimize=[(8, 9), (8, 9), (8, 9), (6, 7), (4, 5), (0, 1), (0, 1), (3, 4), (2, 3), (1, 2), (0, 1)])
