/** Peças comuns aos quatro dialetos.
 *
 *  Nenhum gerador recalcula índice, ordem de eixo ou nome de tensor: tudo vem
 *  de `ContractNetwork`, que por sua vez vem da atribuição de índices que a
 *  faixa da equação também usa. Se um dialeto precisar de outra forma do mesmo
 *  índice — número, letra, nome —, ela nasce aqui e ele a consome. */

import type { ContractNetwork, ContractTensor } from '../contract/network';
import type { ContractionPath, OrderNode } from '../contract/order';

export type Dialect = 'ncon-matlab' | 'ncon-julia' | 'einsum' | 'quimb' | 'itensor';

export interface CodeOptions {
  /** Bloco de tensores de exemplo no topo. Quem já tem os dados carregados não
   *  quer sobrescrevê-los. */
  examples: boolean;
}

export const DEFAULT_CODE_OPTIONS: CodeOptions = { examples: true };

export interface GeneratedCode {
  dialect: Dialect;
  /** Código pronto, ou nulo quando a rede não permite gerar. */
  source: string | null;
  /** Motivo, quando não dá para gerar. */
  problem: string | null;
}

/** Sequência de pares na ordem em que a árvore os contrai, cada um referindo
 *  posições na lista corrente de operandos — é o formato que o `opt_einsum`
 *  aceita em `optimize=`, e o que a animação do M4 vai percorrer. */
export function pairSequence(path: ContractionPath, count: number): [number, number][] {
  if (!path.tree) return [];
  const pares: [number, number][] = [];
  let corrente: number[][] = Array.from({ length: count }, (_, i) => [i]);

  const percorrer = (node: OrderNode): number[] => {
    if (node.kind === 'leaf') return [node.tensor];
    const esquerda = percorrer(node.left);
    const direita = percorrer(node.right);
    const i = corrente.findIndex((g) => mesmoGrupo(g, esquerda));
    const j = corrente.findIndex((g) => mesmoGrupo(g, direita));
    const [a, b] = i < j ? [i, j] : [j, i];
    pares.push([a, b]);
    const fundido = [...esquerda, ...direita];
    corrente = corrente.filter((_, k) => k !== a && k !== b);
    corrente.push(fundido);
    return fundido;
  };

  percorrer(path.tree);
  return pares;
}

function mesmoGrupo(a: number[], b: number[]): boolean {
  return a.length === b.length && a.every((x) => b.includes(x));
}

/** Cabeçalho com o custo estimado.
 *
 *  Em inglês, e só ele: o código gerado vai para MATLAB, Julia e Python, é
 *  colado em repositório e mandado para colaborador. A interface é bilíngue; o
 *  artefato que sai dela fala a língua das ferramentas de destino. */
export function header(
  net: ContractNetwork,
  path: ContractionPath,
  marca: string,
  options: CodeOptions,
): string[] {
  const ordem =
    path.method === 'exhaustive'
      ? 'optimal (exhaustive search)'
      : path.method === 'greedy'
        ? 'greedy heuristic'
        : 'fixed by hand';
  const linhas = [
    `${marca} Generated by MOIRA from the diagram.`,
    `${marca} Contraction order: ${ordem}.`,
    `${marca} Estimated cost: ${formatFlops(path.flops)} operations; scaling ${scalingLabel(path)}.`,
    `${marca} Largest intermediate: ${codeCount(path.peakElements)} elements.`,
  ];
  if (net.assumed > 0) {
    linhas.push(
      `${marca} ${net.assumed} ${net.assumed === 1 ? 'index has' : 'indices have'} no declared dimension; 2 assumed.`,
    );
  }
  // O MOIRA desenha, ordena e traduz; dados numéricos são entrada de quem usa.
  // Dizer isso no cabeçalho evita a primeira dúvida de quem cola o trecho.
  linhas.push(
    `${marca}`,
    options.examples
      ? `${marca} The tensors below are YOUR input. The random block exists only so this`
      : `${marca} The tensors below are YOUR input — MOIRA does not produce numerical data.`,
    options.examples
      ? `${marca} snippet runs as-is; replace it with your own data.`
      : `${marca} Declare them before running, with the shapes listed here.`,
  );
  return linhas;
}

/** Uma linha por tensor, com a forma que ele precisa ter. */
export function shapeComments(net: ContractNetwork, marca: string): string[] {
  const nota = net.tensors.some((t) => t.conjugate)
    ? [`${marca} Tensors marked (conjugate) enter the contraction conjugated:`,
       `${marca} pass the conjugated data in those slots.`]
    : [];
  return nota.concat(net.tensors.map(
    (t) =>
      `${marca} ${t.code}: ${t.axes.map((a) => `${a.code}=${a.dim}`).join(' × ')}` +
      (t.conjugate ? '  (conjugate)' : ''),
  ));
}

const SOBRESCRITO = '⁰¹²³⁴⁵⁶⁷⁸⁹';

/** `pretty` põe expoentes em sobrescrito Unicode, para a tela. Dentro do
 *  código gerado fica `^2`, que é seguro em comentário de qualquer dialeto. */
export function scalingLabel(path: ContractionPath, pretty = false): string {
  if (path.costliest.length === 0) return 'O(1)';
  const partes = path.costliest.map(({ dim, power }) => {
    const base = dim === path.chi ? 'χ' : String(dim);
    if (power === 1) return base;
    return pretty
      ? base + String(power).replace(/\d/g, (d) => SOBRESCRITO[Number(d)]!)
      : `${base}^${power}`;
  });
  return `O(${partes.join('·')})`;
}

export function formatFlops(n: number): string {
  if (!Number.isFinite(n)) return '∞';
  if (n < 1e4) return String(Math.round(n));
  return n.toExponential(2).replace('e+', '×10^');
}

/** Para a interface, no idioma de quem lê. */
export function formatCount(n: number, locale = 'pt-BR'): string {
  return Number.isFinite(n) ? n.toLocaleString(locale) : '∞';
}

/** Para dentro do código gerado: vírgula como separador de milhar, que é o que
 *  se lê num comentário de MATLAB ou de Python em qualquer lugar. */
function codeCount(n: number): string {
  return Number.isFinite(n) ? n.toLocaleString('en-US') : 'unbounded';
}

/** Ordem em que os tensores entram na lista de operandos do código: a ordem de
 *  leitura do canvas, a mesma dos fatores da fórmula. */
export function operands(net: ContractNetwork): ContractTensor[] {
  return net.tensors;
}

/** Bloco de tensores de exemplo, na sintaxe de cada dialeto. Sem ele o primeiro
 *  erro de quem cola o trecho é `NameError`, e o código deixa de ser ferramenta
 *  para virar demonstração. */
export function exampleBlock(
  net: ContractNetwork,
  marca: string,
  linha: (t: ContractTensor) => string,
): string[] {
  // Um tensor conjugado recebe dados independentes, e não o conjugado de
  // outro: o modelo marca que ele é conjugado, não de quem. Inventar a relação
  // seria adivinhar, e o número sairia certo por acidente.
  const temConjugado = net.tensors.some((t) => t.conjugate);
  return [
    `${marca} Example data — replace with your own tensors.`,
    // Quem roda dois dialetos e compara os números suspeita do programa. O
    // aviso custa uma linha e evita um relatório de defeito que não é defeito.
    `${marca} Each language draws its own random numbers, so the value printed`,
    `${marca} here is NOT comparable across dialects. Only your own data is.`,
    ...(temConjugado
      ? [`${marca} Conjugate tensors get independent random data here, not the`,
         `${marca} conjugate of their partner — MOIRA marks that a tensor is`,
         `${marca} conjugated, not whose conjugate it is.`]
      : []),
    ...operands(net).map(linha),
    '',
  ];
}
